# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180124_1057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'staff', 'verbose_name_plural': 'staffs'},
        ),
    ]
