# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-25 12:10
from __future__ import unicode_literals

import apps.users.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180124_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='position',
            field=models.CharField(default='', max_length=32, verbose_name='position'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, verbose_name='logo'),
        ),
    ]
