# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-26 07:23
from __future__ import unicode_literals

import apps.users.models.profile
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180125_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_confirmed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='second_name',
        ),
        migrations.AddField(
            model_name='chief',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='chief',
            name='email_confirmed',
            field=models.BooleanField(default=False, verbose_name='email подтвержден'),
        ),
        migrations.AddField(
            model_name='chief',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='имя'),
        ),
        migrations.AddField(
            model_name='chief',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='фамилия'),
        ),
        migrations.AddField(
            model_name='chief',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='chief',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=apps.users.models.profile.upload_file, verbose_name='фото'),
        ),
        migrations.AddField(
            model_name='chief',
            name='second_name',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='отчество'),
        ),
        migrations.AddField(
            model_name='staff',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='staff',
            name='email_confirmed',
            field=models.BooleanField(default=False, verbose_name='email подтвержден'),
        ),
        migrations.AddField(
            model_name='staff',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='имя'),
        ),
        migrations.AddField(
            model_name='staff',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='фамилия'),
        ),
        migrations.AddField(
            model_name='staff',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='staff',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=apps.users.models.profile.upload_file, verbose_name='фото'),
        ),
        migrations.AddField(
            model_name='staff',
            name='second_name',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='отчество'),
        ),
    ]
