# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-26 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180126_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chief',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chiefs', to='common.Country', verbose_name='country'),
        ),
    ]
