# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-29 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20180126_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(default='', max_length=32, verbose_name='name')),
                ('label', models.CharField(default='', max_length=32, verbose_name='label')),
                ('logo', models.ImageField(default=None, upload_to='', verbose_name='logo')),
            ],
            options={
                'verbose_name_plural': 'accesses',
                'verbose_name': 'access',
            },
        ),
        migrations.CreateModel(
            name='StaffAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.Access', verbose_name='access')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='users.Staff', verbose_name='staff')),
            ],
            options={
                'verbose_name_plural': 'staff accesses',
                'verbose_name': 'staff access',
            },
        ),
    ]
