# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180129_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chief',
            name='phones',
            field=models.ManyToManyField(blank=True, related_name='_chief_phones_+', to='common.Phone', verbose_name='phones'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phones',
            field=models.ManyToManyField(blank=True, related_name='_staff_phones_+', to='common.Phone', verbose_name='phones'),
        ),
    ]
