# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-26 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='option',
            field=models.CharField(blank=True, default='', max_length=8, null=True, verbose_name='option'),
        ),
    ]
