# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('latitude', models.CharField(default='', max_length=64, verbose_name='latitude')),
                ('longitude', models.CharField(default='', max_length=64, verbose_name='longitude')),
                ('house', models.CharField(default='', max_length=16, verbose_name='house')),
                ('building', models.CharField(default='', max_length=8, verbose_name='building')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('value', models.FloatField(default=0.0, verbose_name='value')),
            ],
            options={
                'verbose_name': 'distance',
                'verbose_name_plural': 'distances',
            },
        ),
        migrations.CreateModel(
            name='DistanceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(default='', max_length=32, verbose_name='name')),
            ],
            options={
                'verbose_name': 'distance type',
                'verbose_name_plural': 'distance types',
            },
        ),
        migrations.CreateModel(
            name='EquipmentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('label', models.CharField(default='', max_length=64, verbose_name='label')),
            ],
            options={
                'verbose_name': 'equipment item',
                'verbose_name_plural': 'equipment items',
            },
        ),
        migrations.CreateModel(
            name='EquipmentSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(default='', max_length=32, verbose_name='title')),
                ('label', models.CharField(default='', max_length=128, verbose_name='label')),
            ],
            options={
                'verbose_name': 'equipment section',
                'verbose_name_plural': 'equipment sections',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(default='', max_length=64, verbose_name='name')),
                ('registration_from', models.DateTimeField(default=None, verbose_name='registration from')),
                ('registration_to', models.DateTimeField(default=None, verbose_name='registration to')),
                ('phone', models.CharField(default='', max_length=32, verbose_name='phone')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='email')),
                ('website', models.CharField(default='', max_length=64, verbose_name='website')),
                ('description', models.CharField(default='', max_length=1024, verbose_name='description')),
                ('stars', models.IntegerField(default=1, verbose_name='stars')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hotels.Address', verbose_name='hotel address')),
            ],
            options={
                'verbose_name': 'hotel',
                'verbose_name_plural': 'hotels',
            },
        ),
        migrations.CreateModel(
            name='HotelEquipmentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('equipment_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hotels.EquipmentItem', verbose_name='equipment item')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_items', to='hotels.Hotel', verbose_name='hotel')),
            ],
            options={
                'verbose_name': 'hotel equipment item',
                'verbose_name_plural': 'hotel equipment item',
            },
        ),
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(default='', max_length=32, verbose_name='name')),
            ],
            options={
                'verbose_name': 'location type',
                'verbose_name_plural': 'location types',
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(default='', max_length=64, verbose_name='name')),
            ],
            options={
                'verbose_name': 'street',
                'verbose_name_plural': 'streets',
            },
        ),
        migrations.CreateModel(
            name='StreetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(default='', max_length=32, verbose_name='name')),
            ],
            options={
                'verbose_name': 'street type',
                'verbose_name_plural': 'street types',
            },
        ),
        migrations.AddField(
            model_name='street',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streets', to='hotels.StreetType', verbose_name='type'),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hotels.EquipmentSection', verbose_name='section'),
        ),
        migrations.AddField(
            model_name='distance',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances', to='hotels.DistanceType', verbose_name='type'),
        ),
        migrations.AddField(
            model_name='address',
            name='distance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_addresses', to='hotels.Distance', verbose_name='distance'),
        ),
        migrations.AddField(
            model_name='address',
            name='location_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_addresses', to='hotels.LocationType', verbose_name='location type'),
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_addresses', to='hotels.Street', verbose_name='street'),
        ),
    ]
