# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20180201_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('first_name', models.CharField(default='', max_length=64, verbose_name='first_name')),
                ('second_name', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='second_name')),
                ('last_name', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='last_name')),
                ('email', models.EmailField(blank=True, default='', max_length=64, null=True, verbose_name='email')),
                ('agent', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='agent')),
                ('information', models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='information')),
            ],
            options={
                'verbose_name': 'guest',
                'verbose_name_plural': 'guests',
            },
        ),
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('number', models.CharField(default='', max_length=8, verbose_name='number')),
                ('price', models.FloatField(default=0.0, verbose_name='price')),
                ('title', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='title')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.Hotel', verbose_name='hotel')),
            ],
            options={
                'verbose_name': 'hotel room',
                'verbose_name_plural': 'hotel rooms',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('arrival_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='arrival_date')),
                ('leave_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='leave_date')),
                ('payment_status', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='payment_status')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='hotels.Guest', verbose_name='guest')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='hotels.HotelRoom', verbose_name='room')),
            ],
            options={
                'verbose_name': 'room order',
                'verbose_name_plural': 'room orders',
            },
        ),
    ]
