# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-06 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_guest_hotelroom_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distance',
            name='type',
        ),
        migrations.RemoveField(
            model_name='street',
            name='type',
        ),
        migrations.AddField(
            model_name='address',
            name='distance_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hotels.DistanceType', verbose_name='distance type'),
        ),
        migrations.AddField(
            model_name='address',
            name='street_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hotels.StreetType', verbose_name='street type'),
        ),
        migrations.AlterField(
            model_name='address',
            name='distance',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='distance'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='street'),
        ),
        migrations.DeleteModel(
            name='Distance',
        ),
        migrations.DeleteModel(
            name='Street',
        ),
    ]
