# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-22 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_auto_20180220_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomtype',
            options={'verbose_name': 'room type', 'verbose_name_plural': 'room types'},
        ),
    ]
