# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-11 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_auto_20180222_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtime',
            name='type',
            field=models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('BRUNCH', 'Brunch'), ('DINNER', 'Dinner')], default='BREAKFAST', max_length=32, verbose_name='type'),
        ),
    ]
